// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TreeStore.Models.Entities
{
    public partial class Favorite
    {
        public int FavoriteId { get; set; }
        public int CustomerId { get; set; }
        public int ProductId { get; set; }
        public DateTime CreateOn { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}