// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace TreeStore.Models.Entities
{
    public partial class GetListOrderByCustomerIdSPResult
    {
        public int OrderId { get; set; }
        public DateTime OrderDate { get; set; }
        [Column("TotalAmount", TypeName = "decimal(18,2)")]
        public decimal TotalAmount { get; set; }
        public short State { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int Quantity { get; set; }
        public int PriceOutput { get; set; }
        public string CategoryName { get; set; }
        public bool? IsPaid { get; set; }
    }
}
