// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace TreeStore.Models.Entities
{
    public partial class GetListProductSPResult
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public int PriceOutput { get; set; }
        public bool? IsActive { get; set; }
        public int Quantity { get; set; }
        public int CategoryId { get; set; }
        public string Img { get; set; }
        public string Img2 { get; set; }
        public string Img3 { get; set; }

        public string CategoryName { get; set; }
    }
}
