// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace TreeStore.Models.Entities
{
    public partial class GetReviewInfoWithCustomerResult
    {
        public int ReviewId { get; set; }
        public int ProductId { get; set; }
        public string Comment { get; set; }
        public DateTime CreateOn { get; set; }
        public bool? IsActive { get; set; }
        public string FullName { get; set; }
    }
}
