// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using TreeStore.Models.Entities;

namespace TreeStore.Models.Entities
{
    public partial interface ITreeStoreDBContextProcedures
    {
        Task<List<GetDetailProductOrderSPResult>> GetDetailProductOrderSPAsync(int? OrderId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetListOrderByCustomerIdSPResult>> GetListOrderByCustomerIdSPAsync(int? CustomerId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetListOrderSPResult>> GetListOrderSPAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetListProductSPResult>> GetListProductSPAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetReviewInfoWithCustomerResult>> GetReviewInfoWithCustomerAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
