// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TreeStore.Models.Entities
{
    public partial class Order
    {
        public Order()
        {
            ProductOrders = new HashSet<ProductOrder>();
            Promotions = new HashSet<Promotion>();
        }

        public int OrderId { get; set; }
        public int? UserId { get; set; }
        public int CustomerId { get; set; }
        public short State { get; set; }
        public string Note { get; set; }
        public DateTime CreateOn { get; set; }
        public decimal TotalAmount { get; set; }
        public int? PromotionId { get; set; }
        public bool? IsPaid { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ProductOrder> ProductOrders { get; set; }
        public virtual ICollection<Promotion> Promotions { get; set; }
    }
}