// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TreeStore.Models.Entities
{
    public partial class Product
    {
        public Product()
        {
            Favorites = new HashSet<Favorite>();
            ProductOrders = new HashSet<ProductOrder>();
            Reviews = new HashSet<Review>();
        }

        public int ProductId { get; set; }
        public string Name { get; set; }
        public int PriceInput { get; set; }
        public int PriceOutput { get; set; }
        public string Img { get; set; }
        public bool? IsSell { get; set; }
        public bool? IsActive { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public int Quantity { get; set; }
        public short SaleOff { get; set; }
        public int CategoryId { get; set; }
        public bool IsBanner { get; set; }
        public bool IsFeather { get; set; }
        public bool IsSpecialOffer { get; set; }
        public bool IsPopular { get; set; }
        public string BannerImg { get; set; }
        public string IntroduceBannerHtml { get; set; }
        public string Slug { get; set; }
        public string Img2 { get; set; }
        public string Img3 { get; set; }

        public virtual Category Category { get; set; }
        public virtual ICollection<Favorite> Favorites { get; set; }
        public virtual ICollection<ProductOrder> ProductOrders { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}