// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TreeStore.Models.Entities
{
    public partial class Promotion
    {
        public int PromotionId { get; set; }
        public string ProgramName { get; set; }
        public string PromotionCode { get; set; }
        public string Description { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal MinimumPurchaseAmount { get; set; }
        public int? UsageLimit { get; set; }
        public bool IsActive { get; set; }
        public int? OrderId { get; set; }

        public virtual Order Order { get; set; }
    }
}